/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SincronosRouteImport } from './routes/sincronos'
import { Route as PagamentoRouteImport } from './routes/pagamento'
import { Route as ObrigadoRouteImport } from './routes/obrigado'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiProcessOrderRouteImport } from './routes/api/process-order'
import { Route as ApiCreateOrderRouteImport } from './routes/api/create-order'

const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SincronosRoute = SincronosRouteImport.update({
  id: '/sincronos',
  path: '/sincronos',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoRoute = PagamentoRouteImport.update({
  id: '/pagamento',
  path: '/pagamento',
  getParentRoute: () => rootRouteImport,
} as any)
const ObrigadoRoute = ObrigadoRouteImport.update({
  id: '/obrigado',
  path: '/obrigado',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProcessOrderRoute = ApiProcessOrderRouteImport.update({
  id: '/api/process-order',
  path: '/api/process-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCreateOrderRoute = ApiCreateOrderRouteImport.update({
  id: '/api/create-order',
  path: '/api/create-order',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/obrigado': typeof ObrigadoRoute
  '/pagamento': typeof PagamentoRoute
  '/sincronos': typeof SincronosRoute
  '/sobre': typeof SobreRoute
  '/api/create-order': typeof ApiCreateOrderRoute
  '/api/process-order': typeof ApiProcessOrderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/obrigado': typeof ObrigadoRoute
  '/pagamento': typeof PagamentoRoute
  '/sincronos': typeof SincronosRoute
  '/sobre': typeof SobreRoute
  '/api/create-order': typeof ApiCreateOrderRoute
  '/api/process-order': typeof ApiProcessOrderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/obrigado': typeof ObrigadoRoute
  '/pagamento': typeof PagamentoRoute
  '/sincronos': typeof SincronosRoute
  '/sobre': typeof SobreRoute
  '/api/create-order': typeof ApiCreateOrderRoute
  '/api/process-order': typeof ApiProcessOrderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/obrigado'
    | '/pagamento'
    | '/sincronos'
    | '/sobre'
    | '/api/create-order'
    | '/api/process-order'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/obrigado'
    | '/pagamento'
    | '/sincronos'
    | '/sobre'
    | '/api/create-order'
    | '/api/process-order'
  id:
    | '__root__'
    | '/'
    | '/obrigado'
    | '/pagamento'
    | '/sincronos'
    | '/sobre'
    | '/api/create-order'
    | '/api/process-order'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ObrigadoRoute: typeof ObrigadoRoute
  PagamentoRoute: typeof PagamentoRoute
  SincronosRoute: typeof SincronosRoute
  SobreRoute: typeof SobreRoute
  ApiCreateOrderRoute: typeof ApiCreateOrderRoute
  ApiProcessOrderRoute: typeof ApiProcessOrderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sincronos': {
      id: '/sincronos'
      path: '/sincronos'
      fullPath: '/sincronos'
      preLoaderRoute: typeof SincronosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento': {
      id: '/pagamento'
      path: '/pagamento'
      fullPath: '/pagamento'
      preLoaderRoute: typeof PagamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/obrigado': {
      id: '/obrigado'
      path: '/obrigado'
      fullPath: '/obrigado'
      preLoaderRoute: typeof ObrigadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/process-order': {
      id: '/api/process-order'
      path: '/api/process-order'
      fullPath: '/api/process-order'
      preLoaderRoute: typeof ApiProcessOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/create-order': {
      id: '/api/create-order'
      path: '/api/create-order'
      fullPath: '/api/create-order'
      preLoaderRoute: typeof ApiCreateOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ObrigadoRoute: ObrigadoRoute,
  PagamentoRoute: PagamentoRoute,
  SincronosRoute: SincronosRoute,
  SobreRoute: SobreRoute,
  ApiCreateOrderRoute: ApiCreateOrderRoute,
  ApiProcessOrderRoute: ApiProcessOrderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
